import './globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '메이플 | 스트리머 랭킹',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
